openapi: 3.0.1
info:
  title: Demo Plugin API
  version: "1.0"
paths:
  /hello:
    get:
      summary: Returns a greeting
      operationId: getHello
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
